services:
  db:
    image: mariadb:10.3
    # environment:
      # MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - holy
  
  php:
    build:
      context: .boing/docker/php
    volumes:
      - .:/srv
    networks:
      - holy
  
  consumer:
    depends_on:
      - php
    build:
      context: .boing/docker/php
    command: php bin/console messenger:consume scheduler_weekScrap
    volumes:
      - .:/srv
    networks:
      - holy

  web:
    depends_on:
      - php
    build:
      context: .boing/docker/nginx/symfony
    volumes:
      - ./public:/srv/public
    networks:
      - holy

volumes:
  db_data:

networks:
  holy:
