services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/DTO/'
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/Kernel.php'
            - '../src/Utils.php'

    App\Command\ScrapNewProductsCommand:
        arguments:
            # $scraper: '@App\Service\Scraping\Scraper'
            $baseUrl: '%env(HOLY_URL)%'
            $allProductsPath: '%env(HOLY_ALL_PRODUCTS_PATH)%'

    App\Command\Mock\MockAllProductsPageCommand:
        arguments:
            $baseUrl: '%env(HOLY_URL)%'
            $allProductsPath: '%env(HOLY_ALL_PRODUCTS_PATH)%'

    App\Service\Scraping\Mock\ScraperMock:
        arguments:
            $mockPath: '%env(MOCK_PATH)%'

    App\Service\Crawling\ProductCrawler:
        arguments:
            $mockPath: '%env(MOCK_PATH)%'

# when@dev:
#     App\Service\Scraping\Scraper: '@App\Service\Scraping\Mock\ScraperMock'
